#!/bin/sh


start_vm(){
	MACHINE_NAME=$1
	IS_UP=$(vboxmanage showvminfo $MACHINE_NAME | grep -c "running (since")
	if [ $IS_UP eq 0 ]; then
		#VBoxManage startvm $MACHINE_NAME
		echo start machine
	fi
}
start_vm "Win7-ENT"
