#!/bin/sh
#read -e -p 

. ./sql-base.sh

SQL_MODULE=/PruCaseHandling/sqlScripts/oracle/updates/Pru_R3_0_1/RejectIllustrationPD
REVISION=11602
PROCESS_DESCRIPTOR_NAME=RejectIllustration
PROCESS_DESCRIPTOR_DESCRIPTION="It rejects an dillustration"
REPOSITORY_PATH=PruCaseHandling.Implementation.Illustrations.Actions.RejectIllustration
#Type 2. Action 3. SLA
TYPE=2

SQL="INSERT INTO EVA_PROCESS_DESCRIPTOR (ID, ENV_ID, NAME, REPOSITORY_PATH, CONFIG_PROCESS_ID, IS_DELETED, TYPE) VALUES (@PD.$PROCESS_DESCRIPTOR_NAME, @ENV.Dflt, '$PROCESS_DESCRIPTOR_NAME', '$REPOSITORY_PATH', null, 'N', $TYPE);\n
INSERT INTO EVA_PROCESS_DESCRIPTOR_LOC (ID, ENV_ID, LOCALE, DISPLAY_NAME, DESCRIPTION) VALUES (@PD.$PROCESS_DESCRIPTOR_NAME, @ENV.Dflt, 'en-GB', '$PROCESS_DESCRIPTOR_NAME', '$PROCESS_DESCRIPTOR_DESCRIPTION');"

create_sql_module $SQL_MODULE $REVISION "$SQL"
