INSERT INTO FU_USER (ID,USERNAME, LOCALE_ID, LOCALE_ENV_ID, IS_DELETED, VIRTUAL_ENVIRONMENT_ID, VIRTUAL_ENVIRONMENT_ENV_ID)
VALUES (@USER.agent,'agent',@LOC.EnglishGB, @ENV.Dflt, 'N',1,@ENV.Dflt);

INSERT INTO AGENT (USERNAME,PASSWORD,FULLNAME,EXPIRES,PERSON_ID,CONNECTON,DISABLED,GRACE,CREATED,ALLOWCONCURRENT,CONSISTENTIPONLY,LOGINFAILURES,LASTLOGGEDIN,SALT,ENCRYPTION_CLASSNAME,TENANT_ID) VALUES ('agent','994a90c301ce14842adcd23feb94aefe588ba7c4d9aab114dca1244951a48e55','Pedro picapiedra',{ts '2999-12-31 00:00:00'},1,1,'no',0,SYSDATE,1,'no',0,SYSDATE,'pyuQbZQ/cQk=','com.gtnet.common.security.algorithms.SHA256','default');

INSERT INTO CE_PERSON (ID, FIRST_NAME, FIRST_NAME_UPPER, MIDDLE_NAME, LAST_NAME, LAST_NAME_UPPER, PREVIOUS_LAST_NAME, GENDER_ID, GENDER_ENV_ID, TITLE_ID, TITLE_ENV_ID, DATE_OF_BIRTH, IS_DELETED)
VALUES (@PERSON.agent, 'Pedro', 'PEDRO', NULL, 'Picapiedra', 'PICAPIEDRA', NULL, 1, @ENV.Dflt, @TITLE.Mrs, @ENV.Dflt, SYSDATE, 'N');

INSERT INTO CE_AGENT (ID, USER_ID)
VALUES (@PERSON.agent, @USER.agent);

INSERT INTO FD_USER_PROFILE_TYPE ( USER_ID, PROFILE_TYPE_ID, PROFILE_TYPE_ENV_ID, IS_DELETED)
VALUES (@USER.agent, @PROFILE.AGENT, @ENV.Dflt, 'N');

INSERT INTO GTCC_MEMBEROFBLEND (AGENT_ID, BLEND_ID)
VALUES (@PERSON.agent, @BLEND.Email);
--INSERT INTO EVA_ENTITY__ENTITLEMENT (ENTITLEMENT_ID, ENTITLEMENT_ENV_ID, ENTITY_ID, ENTITY_ENV_ID, ENTITY_TYPE_ID, ENTITY_TYPE_ENV_ID, IS_DELETED, RELEASEID)
--VALUES (@ENTLMNT.DCC0, @ENV.Dflt, @PERSON.agent, @ENV.Dflt, @ET.Agent, @ENV.Dflt, 'N', -1);


INSERT INTO EVA_ENTITY_PROPERTY (ENTITY_ID, ENTITY_ENV_ID, ENTITY_TYPE_ID, ENTITY_TYPE_ENV_ID, PROPERTY_NAME, PROPERTY_VALUE)
values (@PERSON.agent, @ENV.Dflt, @ET.Agent, @ENV.Dflt, 'DEFAULT_EMAIL_FROM_ADDRESS', 'kirsty.davidson@dhl.com');


--INSERT INTO CW_ROUTING_ENTITLEMENT(ENTITY_ID, ENTITY_ENV_ID, ENTITY_TYPE_ID, ENTITY_TYPE_ENV_ID, ENTITLEMENT_ID, ENTITLEMENT_ENV_ID, NAME, RELEASE_ID) VALUES(@PERSON.agent, @ENV.Dflt, @ET.Agent, @ENV.Dflt, @ENTLMNT.QualityAssuranceRepresentative, @ENV.Dflt, 'QA', @RELEASE.ID);



INSERT INTO CWQ_ENTITY__QUEUE (ENTITY_ID, ENTITY_ENV_ID, ENTITY_TYPE_ID, ENTITY_TYPE_ENV_ID, QUEUE_ID, QUEUE_ENV_ID) VALUES (@PERSON.agent, @ENV.Dflt, @ET.Agent, @ENV.Dflt, @QUEUE.DEFAULTQUEUE, @ENV.Dflt); 
