#!/bin/sh
#read -e -p 

. ./sql-base.sh

SQL_MODULE=/PruCaseHandling/sqlScripts/oracle/updates/Pru_R3_0_1/BaseIllustrationED
REVISION=11653
ENTITY_DEF_NAME=PruBaseIllustrationED
INTERFACE_PATH=PruCaseHandling.API.EIPruBaseIllustration
LOGICAL_OBJ_PATH=PruCaseHandling.Implementation.Illustrations.Objects.BasePruIllustration
SUPER_ENTITY_DEFINITION=PersistableEntity
DISPLAY_NAME="Base Illustration"


SQL="INSERT INTO EVA_ENTITY_DEFINITION (ID, ENV_ID, NAME, TYPE_ID, TYPE_ENV_ID,  LOGICAL_OBJ_PATH, INTERFACE_PATH, IS_DELETED, IS_BASIC, ICON_PATH, INSTANCE_ICON_PATH, SUPER_ENTITY_DEFINITION, SUPER_ENTITY_DEFINITION_ENV_ID, RELEASE_ID ) VALUES (@ED.$ENTITY_DEF_NAME, @ENV.Dflt, '$ENTITY_DEF_NAME', @ET.$EN$ENTITY_DEF_NAME, @ENV.Dflt, '$LOGICAL_OBJ_PATH', '$INTERFACE_PATH', 'N', 'Y',null, null, @ED.$SUPER_ENTITY_DEFINITION,@ENV.Dflt,@RELEASE.ID);\n
INSERT INTO EVA_ENTITY_DEFINITION_LOC (ID, ENV_ID, LOCALE, DISPLAY_NAME, DESCRIPTION) VALUES (@ED.$ENTITY_DEF_NAME, @ENV.Dflt, 'en-GB', '$DISPLAY_NAME', '$DISPLAY_NAME');"

create_sql_module $SQL_MODULE $REVISION "$SQL"
