#!/bin/sh
#read -e -p 

. ./sql-base.sh

SQL_MODULE=/SPENConnection/sqlScripts/oracle/updates/CR_RELEASE_7/PostQuoteCustomerMoodTag
REVISION=15368


SQL="INSERT INTO EVA_TAG (ID, ENV_ID, RELEASE_ID, TAGSET_ID, TAGSET_ENV_ID, TAGSET_RELEASE_ID, PARENT_TAG, PARENT_TAG_ENV_ID, PARENT_TAG_RELEASE_ID, PREVIOUS_TAG, PREVIOUS_TAG_ENV_ID, PREVIOUS_TAG_RELEASE_ID, NAME, IS_SYSTEM, IS_DELETED, IS_RETIRED, EXPAND_DIRECTION, CREATED_DATE, LAST_MODIFIED_DATE, LEFT_VAL, RIGHT_VAL, DEPTH_VAL, DISPLAY_ORDER) VALUES (\n
@TAG.PostQuoteContactMood,  -- ID
@ENV.Dflt,  -- ENV_ID
@RELEASE.ID,  -- RELEASE_ID
@TAG.PostQuoteContactMood,  -- TAGSET_ID
@ENV.Dflt,  -- TAGSET_ENV_ID
@RELEASE.ID,  -- TAGSET_RELEASE_ID
NULL,  -- PARENT_TAG
NULL,  -- PARENT_TAG_ENV_ID
NULL,  -- PARENT_TAG_RELEASE_ID
NULL,  -- PREVIOUS_TAG
NULL,  -- PREVIOUS_TAG_ENV_ID
NULL,  -- PREVIOUS_TAG_RELEASE_ID
'postQuoteContactMood',  -- NAME
'N',  -- IS_SYSTEM
'N',  -- IS_DELETED
'N',  -- IS_RETIRED
'NONE',  -- EXPAND_DIRECTION
TO_DATE('04/03/2017 17:01:40 PM','MM/DD/YYYY HH:MI:SS AM'),  -- CREATED_DATE
TO_DATE('04/03/2017 17:01:40 PM','MM/DD/YYYY HH:MI:SS AM'),  -- LAST_MODIFIED_DATE
0,  -- LEFT_VAL
13,  -- RIGHT_VAL
0,  -- DEPTH_VAL
'1' -- DISPLAY_ORDER
);
INSERT INTO EVA_TAG_LOC (ID, ENV_ID, RELEASE_ID, LOCALE, DESCRIPTION, REPORTING_LABEL) VALUES (
@TAG.PostQuoteContactMood,  -- ID
@ENV.Dflt,  -- ENV_ID
@RELEASE.ID,  -- RELEASE_ID
'en-GB',  -- LOCALE
'Post Quote Contact Mood',  -- DESCRIPTION
NULL -- REPORTING_LABEL
);
INSERT INTO EVA_TAG_DISPLAY_NAME (ID, ENV_ID, RELEASE_ID, DISPLAY_NAME_TYPE_ID, DISPLAY_NAME_TYPE_ENV_ID, DISPLAY_NAME_TYPE_RELEASE_ID) VALUES (
@TAG.PostQuoteContactMood,  -- ID
@ENV.Dflt,  -- ENV_ID
@RELEASE.ID,  -- RELEASE_ID
@TDNT.ShortNameType,  -- DISPLAY_NAME_TYPE_ID
@ENV.Dflt,  -- DISPLAY_NAME_TYPE_ENV_ID
@RELEASE.ID -- DISPLAY_NAME_TYPE_RELEASE_ID
);
INSERT INTO EVA_TAG_DISPLAY_NAME_LOC (ID, ENV_ID, RELEASE_ID, LOCALE, DISPLAY_NAME, DISPLAY_NAME_TYPE_ID, DISPLAY_NAME_TYPE_ENV_ID, DISPLAY_NAME_TYPE_RELEASE_ID) VALUES (
@TAG.PostQuoteContactMood,  -- ID
@ENV.Dflt,  -- ENV_ID
@RELEASE.ID,  -- RELEASE_ID
'en-GB',  -- LOCALE
'Post Quote Contact Mood',  -- DISPLAY_NAME
@TDNT.ShortNameType,  -- DISPLAY_NAME_TYPE_ID
@ENV.Dflt,  -- DISPLAY_NAME_TYPE_ENV_ID
@RELEASE.ID -- DISPLAY_NAME_TYPE_RELEASE_ID
);

INSERT INTO EVA_TAG (ID, ENV_ID, RELEASE_ID, TAGSET_ID, TAGSET_ENV_ID, TAGSET_RELEASE_ID, PARENT_TAG, PARENT_TAG_ENV_ID, PARENT_TAG_RELEASE_ID, PREVIOUS_TAG, PREVIOUS_TAG_ENV_ID, PREVIOUS_TAG_RELEASE_ID, NAME, IS_SYSTEM, IS_DELETED, IS_RETIRED, EXPAND_DIRECTION, CREATED_DATE, LAST_MODIFIED_DATE, LEFT_VAL, RIGHT_VAL, DEPTH_VAL, DISPLAY_ORDER) VALUES (
@TAG.ContactMood_fully_satisfied,  -- ID
@ENV.Dflt,  -- ENV_ID
@RELEASE.ID,  -- RELEASE_ID
@TAG.PostQuoteContactMood,  -- TAGSET_ID
@ENV.Dflt,  -- TAGSET_ENV_ID
@RELEASE.ID,  -- TAGSET_RELEASE_ID
@TAG.PostQuoteContactMood,  -- PARENT_TAG
@ENV.Dflt,  -- PARENT_TAG_ENV_
@RELEASE.ID,  -- PARENT_TAG_RELEASE_ID
NULL,  -- PREVIOUS_TAG
NULL,  -- PREVIOUS_TAG_ENV_ID
NULL,  -- PREVIOUS_TAG_RELEASE_ID
'contactMood_fully_satisfied',  -- NAME
'N',  -- IS_SYSTEM
'N',  -- IS_DELETED
'N',  -- IS_RETIRED
NULL,  -- EXPAND_DIRECTION
TO_DATE('04/03/2017 17:01:40 PM','MM/DD/YYYY HH:MI:SS AM'),  -- CREATED_DATE
TO_DATE('04/03/2017 17:01:40 PM','MM/DD/YYYY HH:MI:SS AM'),  -- LAST_MODIFIED_DATE
1,  -- LEFT_VAL
2,  -- RIGHT_VAL
1,  -- DEPTH_VAL
NULL -- DISPLAY_ORDER
);
INSERT INTO EVA_TAG_LOC (ID, ENV_ID, RELEASE_ID, LOCALE, DESCRIPTION, REPORTING_LABEL) VALUES (
@TAG.ContactMood_fully_satisfied,  -- ID
@ENV.Dflt,  -- ENV_ID
@RELEASE.ID,  -- RELEASE_ID
'en-GB',  -- LOCALE
'Successful – Fully satisfied',  -- DESCRIPTION
NULL -- REPORTING_LABEL
);
INSERT INTO EVA_TAG_DISPLAY_NAME (ID, ENV_ID, RELEASE_ID, DISPLAY_NAME_TYPE_ID, DISPLAY_NAME_TYPE_ENV_ID, DISPLAY_NAME_TYPE_RELEASE_ID) VALUES (
@TAG.ContactMood_fully_satisfied,  -- ID
@ENV.Dflt,  -- ENV_ID
@RELEASE.ID,  -- RELEASE_ID
@TDNT.ShortNameType,  -- DISPLAY_NAME_TYPE_ID
@ENV.Dflt,  -- DISPLAY_NAME_TYPE_ENV_ID
@RELEASE.ID -- DISPLAY_NAME_TYPE_RELEASE_ID
);
INSERT INTO EVA_TAG_DISPLAY_NAME_LOC (ID, ENV_ID, RELEASE_ID, LOCALE, DISPLAY_NAME, DISPLAY_NAME_TYPE_ID, DISPLAY_NAME_TYPE_ENV_ID, DISPLAY_NAME_TYPE_RELEASE_ID) VALUES (
@TAG.ContactMood_fully_satisfied,  -- ID
@ENV.Dflt,  -- ENV_ID
@RELEASE.ID,  -- RELEASE_ID
'en-GB',  -- LOCALE
'Successful – Fully satisfied',  -- DISPLAY_NAME
@TDNT.ShortNameType,  -- DISPLAY_NAME_TYPE_ID
@ENV.Dflt,  -- DISPLAY_NAME_TYPE_ENV_ID
@RELEASE.ID -- DISPLAY_NAME_TYPE_RELEASE_ID
);"
#create_sql_module $SQL_MODULE $REVISION "$SQL"
sql_tag(){
	echo "$(cat ./add-tag.sql)"
}
TAG_NAME=PostQuoteContactMood
DATE="04/03/2017"
PARENT_TAG=NULL
PARENT_TAG_ENV_ID=NULL
PARENT_TAG_RELEASE_ID=NULL
LEFT_VAL=0
RIGHT_VAL=13
DEPTH_VAL=0
DISPLAY_ORDER=1
DISPLAY_NAME="Post Quote Contact Mood"

SQL=$(eval "echo \"$(sql_tag)\"")

echo "SQL 2 is $SQL"
#	echo "$(cat ./add-tag.sql)"
