INSERT INTO EVA_ENTITLEMENT (ID,ENV_ID,DISPLAY_NAME,IS_DELETED,IS_WORKFLOW_ENTITLEMENT,RELEASE_ID,IS_CONTENT_ENTITLEMENT,SYSTEM_NAME,TENANT_ID,IS_PRIVILEGE_ENTITLEMENT) 
VALUES (@ENTLMNT.${ENT_ID},@ENV.Dflt,'${ENT_DISP_NAME}','N','N',@RELEASE.ID,'N','${ENT_SYSTEM_NAME}','default','N');
