
INSERT INTO EVA_VERB (ID, NAME, PROCESS_DESC_REF_ID, ENTITY_DEF_ID, ENTITY_DEF_ENV_ID, IS_INSTANCE, IS_DEFAULT, IS_INSTANCE_DEFAULT, IS_USER_VISIBLE, RECORD_FOR_WRAPUP, DISPLAY_AT_WRAPUP, RELEASE_ID, IS_LAUNCHABLE_TASK)
VALUES (
@V.$VERB_ID, --ID
'$VERB_NAME', --name 
@PDR.$PROCESS_DESC_REF_ID, --PROCESS_DESC_REF_ID
@ED.$ENTITY_DEF_ID ,--ENTITY_DEF_ID
@ENV.Dflt,--ENTITY_DEF_ENV_ID
'$IS_INSTANCE',--IS_INSTANCE
'N',-- IS_DEFAULT
'N',-- IS_INSTANCE_DEFAULT
'$IS_USER_VISIBLE', --IS_USER_VISABLE
'$RECORD_FOR_WRAPUP', --RECORD_FOR_WRAPUP
'N', --DISPLAY_AT_WRAPUP
@RELEASE.ID, --RELEASE_ID
'$IS_LAUNCHABLE_TASK'
);
INSERT INTO EVA_VERB_LOC (ID, LOCALE, DISPLAY_NAME, DESCRIPTION) VALUES (@V.$VERB_ID, 'en-GB', '$VERB_NAME', '$VERB_NAME');

