INSERT INTO EVA_ENTITY_DEFINITION (ID, ENV_ID, NAME, TYPE_ID, TYPE_ENV_ID, LOGICAL_OBJ_PATH, INTERFACE_PATH, IS_DELETED, IS_BASIC, ICON_PATH, INSTANCE_ICON_PATH, SUPER_ENTITY_DEFINITION, SUPER_ENTITY_DEFINITION_ENV_ID, RELEASE_ID, PERSISTENCE_MANAGER, SUPPORTS_READONLY) VALUES
(@ED.$ENTITY_ID, @ENV.Dflt, '${ENTITY_ID}ED', @ET.$ENTITY_ID, @ENV.Dflt, '$LOGICAL_OBJ_PATH', '$INTERFACE_PATH', 'N', 'N',NULL, NULL, @ED.$SUPER_ENTITY_DEFINITION, @ENV.Dflt, @RELEASE.ID, NULL, 'Y');
INSERT INTO EVA_ENTITY_DEFINITION_LOC(ID, ENV_ID, LOCALE, DISPLAY_NAME, DESCRIPTION, RELEASE_ID) VALUES
(@ED.$ENTITY_ID, @ENV.Dflt, 'en-GB', '$ENTITY_ID', '$ENTITY_ID',@RELEASE.ID);

INSERT INTO EVA_CATEGORY_ENTRY (CATEGORY_ID, CATEGORY_ENV_ID, ENTITY_ID, ENTITY_ENV_ID) VALUES (@EC.SystemGeneral, @ENV.Dflt, @ED.${ENTITY_ID}, @ENV.Dflt);
