
CREATE TABLE $TABLE_NAME
(
	ID NUMBER(9) PRIMARY KEY NOT NULL,
	CREATED_DATE DATE,
	MONEY NUMBER(10,2);
	FULL_NAME NVARCHAR2(100) NOT NULL,
	TAG_CODE NVARCHAR2(30),
	POSTAL_CODE NVARCHAR2(50),
	EMAIL_ADDRESS NVARCHAR2(80),
	CASE_ID NUMBER (9), 
	IS_DELETED CHAR(1),
	CONSTRAINT CASE_ID_FK FOREIGN KEY (CASE_ID) REFERENCES CH_CASE (ID)
);
