INSERT INTO FR_MONITOR (ID,REPOSITORY_PATH,TENANT_ID) VALUES(@FRM.$MONITOR_ID,'$MONITOR_REPO_PATH','default');

INSERT INTO EVA_ENTITY_DEFINITION (ID, ENV_ID, NAME, TYPE_ID, TYPE_ENV_ID, LOGICAL_OBJ_PATH, INTERFACE_PATH, IS_DELETED, IS_BASIC, ICON_PATH, INSTANCE_ICON_PATH, SUPER_ENTITY_DEFINITION, SUPER_ENTITY_DEFINITION_ENV_ID, RELEASE_ID, PERSISTENCE_MANAGER, SUPPORTS_READONLY) VALUES
(@ED.$MONITOR_ID, @ENV.Dflt, '${MONITOR_ID}ED', @ET.$MONITOR_ID, @ENV.Dflt, '$MONITOR_REPO_PATH', 'FrameworkEVA.API.Interfaces.EIEntity', 'N', 'Y', NULL, NULL, NULL, NULL, @RELEASE.ID, NULL, 'Y');
INSERT INTO EVA_ENTITY_DEFINITION_LOC(ID, ENV_ID, LOCALE, DISPLAY_NAME, DESCRIPTION, RELEASE_ID) VALUES
(@ED.$MONITOR_ID, @ENV.Dflt, 'en-GB', 'MONITOR_ID', 'MONITOR_ID',@RELEASE.ID);

INSERT INTO EVA_CATEGORY_ENTRY(CATEGORY_ID, CATEGORY_ENV_ID, ENTITY_ID, ENTITY_ENV_ID) VALUES (
@EC.System, -- CATEGORY_ID
@ENV.Dflt, -- CATEGORY_ENV_ID
@ED.$MONITOR_ID, -- ENTITY_ID
@ENV.Dflt -- ENTITY_ENV_ID
);
INSERT INTO EVA_PROCESS_DESCRIPTOR (ID, ENV_ID, NAME, REPOSITORY_PATH, CONFIG_PROCESS_ID, IS_DELETED,TYPE) VALUES (@PD.Start$MONITOR_ID, @ENV.Dflt, 'Start$MONITOR_ID', '$START_REPO_PATH', NULL, 'N', 0);
INSERT INTO EVA_PROCESS_DESCRIPTOR_LOC (ID, ENV_ID, LOCALE, DISPLAY_NAME, DESCRIPTION) VALUES (@PD.Start$MONITOR_ID, @ENV.Dflt, 'en-GB', 'Start$MONITOR_ID', '');

INSERT INTO EVA_PROCESS_DESC_REFERENCE (ID, PROCESS_DESCRIPTOR_ID, PROCESS_DESCRIPTOR_ENV_ID, CONFIG_ID, IS_SHARED) VALUES (
@PDR.Start$MONITOR_ID, --ID
@PD.Start$MONITOR_ID, --PROCESS_DESCRIPTOR_ID
@ENV.Dflt, --PROCESS_DESCRIPTOR_ENV_ID
NULL, --CONFIG_ID
'N'--IS_SHARED
);
INSERT INTO EVA_VERB (ID, NAME, PROCESS_DESC_REF_ID, ENTITY_DEF_ID, ENTITY_DEF_ENV_ID, IS_INSTANCE, IS_DEFAULT, IS_INSTANCE_DEFAULT, IS_USER_VISIBLE, RECORD_FOR_WRAPUP) VALUES (
@V.Start$MONITOR_ID, --ID
'start', --NAME
@PDR.Start$MONITOR_ID,-- PROCESS_DESC_REF_ID
@ED.$MONITOR_ID, --ENTITY_DEF_ID
@ENV.Dflt, --ENTITY_DEF_ENV_ID
'N', --IS_INSTANCE
'N', --IS_DEFAULT
'N', --IS_INSTANCE_DEFAULT
'N', --IS_USER_VISIBLE
'N'--RECORD_FOR_WRAPUP
);

INSERT INTO EVA_VERB_LOC (ID, LOCALE, DISPLAY_NAME, DESCRIPTION) VALUES (
@V.Start$MONITOR_ID, --ID
'en-GB', --LOCALE
'Start$MONITOR_ID', --DISPLAY_NAME
''--DESCRIPTION
);

INSERT INTO EVA_DYNAMIC_VERB_LIST (ID, ENV_ID, RELEASE_ID, TYPE_ID, TYPE_ENV_ID, ENTITY_TYPE_ID, ENTITY_TYPE_ENV_ID, VERB_NAME, SEQUENCE_NO, TENANT_ID) VALUES (
@EDVL.Start$MONITOR_ID, --ID
@ENV.Dflt, --ENV_ID
@RELEASE.ID, --RELEASE_ID
@EDVLT.RegisterWorkItemListeners, --TYPE_ID
@ENV.Dflt, --TYPE_ENV_ID
@ET.$MONITOR_ID, --ENTITY_TYPE_ID
@ENV.Dflt, --ENTITY_TYPE_ENV_ID
'start', --VERB_NAME
$SEQUENCE_NO, --SEQUENCE_NO
@TENANT.ID -- TENANT_ID
);


